PATH_DATASETS = ""
PATH_DATASETS = ""

PATH_CACHE = ""

PATH_DATAFRAME_TRANSFERABILITY = ""
PATH_DATAFRAME_TRANSFERABILITY_CLASSIFICATION = PATH_DATAFRAME_TRANSFERABILITY + "classification/"

PATH_RESULTS_TRANSFERABILITY = ""